### ISSUE TITLE
Swagger UI code update - Code snippet copy

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#2]
**Skills / SW**:
- Swagger UI

**Description**:
Upgrade the Swagger UI code to include a new function to be displayed as a button or link next to query request / response windows.

-  Copy code snippet to clipboard (request and / or response)

**Deliverables**:
- Updated Swagger UI code enabling the functionality above

**Comment by banders** [comment]
I have created a patch that adds 'Copy Request URL' and 'Copy Response Body' buttons.  The buttons copy the corresponding content to the clipboard.  The patch is in [this branch](https://github.com/banders/swagger-ui/tree/copy-to-clipboard).

**Comment by banders** [comment]
I incorporated the patch into a custom build of swagger-ui for ckanext-openapiviewer.  Pull request is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/22).

**Comment by BK01** [comment]
@BK01 to review this week

**Comment by BK01** [comment]
UAT complete in cat.data...
Ready for PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
