### ISSUE TITLE
Heartbeat - BCDC Data API

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#25]
**Skills / SW**:
- Python, JavaScript (d3 library), HTML, CSS
- GitHub, BCDC

**Description**:
To investigate if it is possible to create a heartbeat page for the following. If possible, build one for each.

**Deliverables**:
- updates to existing scripts as required in the following repo: https://github.com/bcgov/dbcrss

https://catalogue.data.gov.bc.ca/api/3/action/package_search?fq=license_id:22
https://catalogue.data.gov.bc.ca/api/3/action/package_show?id=2da43b9a-0795-42f1-b403-6f1a68f7b99a

**Comment by BK01** [comment]
Create a new heartbeat for each of the following.
https://catalogue.data.gov.bc.ca/api/3/action/package_search?fq=license_id:22
https://catalogue.data.gov.bc.ca/api/3/action/package_show?id=2da43b9a-0795-42f1-b403-6f1a68f7b99a

**Comment by banders** [comment]
@BK01 To clarify: are you requesting the heartbeat script just pings each of the above URLs and graphs the response time?  Or are you also interested in confirming any details about the response content?

I'm curious: for the other APIs we don't test multiple resources.  Why are we testing two resources from the BCDC API?

**Comment by BK01** [comment]
@banders In this case we are simply looking for a graph of response time. Both URLs are included as examples however, only one is needed. Perhaps use the package_search resource.

**Comment by banders** [comment]
@BK01 Thanks for the clarification.  I'll create a heartbeat and graph for the BCDC API.

**Comment by banders** [comment]
@BK01 @ll911 can one of you please modify the Jenkins job to run the heartbeat python script against the BCDC URL?  A python statement like this should work:

`python heartbeat.py -url "https://catalogue.data.gov.bc.ca/api/3/action/package_search?fq=license_id:22" -o ../data/bcdc-heartbeat.txt`

It will save the response to the heartbeat data file in the /data folder.

The command above assumes the execution folder is /src.  Slight changes to local file paths in the above statement will be necessary if executing from a different folder. Best just to use the same relative paths for script and output files as is used by the Jenkins jobs for the other heartbeats.

**Comment by BK01** [comment]
@banders Thanks. DataBC will update the heartbeat Jenkins job.

**Comment by banders** [comment]
@BK01 I added the new graph, and created a link to it from the README in the dbcrss repo:

[https://github.com/bcgov/dbcrss/](https://github.com/bcgov/dbcrss/)

**Comment by BK01** [comment]
Thank you. UAT complete.
