### ISSUE TITLE
Galileo Docker image - On-prem implementation

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#28]
**Skills / SW**:
- Docker, Galileo
*If Amazon becomes an option for BC Gov't, Mashape offers an option for this.

**Team**:
DataBC middleware, Mashape dev team, dev community

**Client**:
WBC is looking for analytics on their new API as of April 2017 which will use the DataBC API Gateway.

**Description**:
Complete the final steps in Galileo install locally using Mashape docker image.

Debugging - with Mashape and dev community

**Deliverables**:
New local implementation of Galileo

**Comment by BK01** [comment]
Any news from Mashape or online post?

**Comment by ll911** [comment]
get a new version from mashape, testing WIP

**Comment by BK01** [comment]
Openshift install scheduled for Feb 14th. Testing to follow.

**Comment by BK01** [comment]
Technical issue continuing. Will place on hold until approval received for cloud deployment.
