### ISSUE TITLE
Swagger UI code update - open in browser

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#3]
**Skills / SW**:
- Swagger UI

**Description**:
Upgrade the Swagger UI code to include a new function to be displayed as a button or link next to query request / response windows.

*Show response body in a new brownser window

-  Open code in browser

**Deliverables**:
- Updated Swagger UI code enabling the functionality above

**Comment by banders** [comment]
I created a custom modification to swagger UI to address this issue in this [branch](https://github.com/banders/swagger-ui/tree/copy-to-clipboard).  The modification adds a new "Open Request URL" button adjacent to the "Copy to Clipboard" button.  

I made a generated a new build of swagger-ui which include this change and all other customizations for DataBC, and I included the new swagger-ui in the ckanext-openapiviewer.  Pull request for ckanext-openapiviewer is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/23).

**Comment by BK01** [comment]
DataBC to perform UAT once merged.

**Comment by BK01** [comment]
UAT successful in cad.data and cat.data. Please proceed to PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
