### ISSUE TITLE
OpenAPI specs - Summary attribute

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#31]
**Skills / SW**:
- OpenAPI spec (swagger 2.0)

**Description**:

- Fork OpenAPI specs located at the following repo.
   https://github.com/bcgov/api-specs
- Add a 'summary' attribute for each resource
- Initially only complete for the BCGNWS OpenAPI spec to be followed by DataBC review and feedback

**Deliverables**:

- Pull request submitted for a new version of the BCGNWS OpenAPI spec (include summary attribute)

**Comment by banders** [comment]
I have added the summary attributes to each resource of the BCGNWS API spec.  The pull request has been merged into the bcgov repo, and the updated spec file is [here](https://github.com/bcgov/api-specs/blob/master/bcgnws/bcgnws.json).

Let me know if you'd like me to add "summary" attributes to the other API spec files.

**Comment by BK01** [comment]
@banders @ll911 Thank you. We will merge the new BCGNWS API spec, review/QA and let you know about additional API specs.

**Comment by BK01** [comment]
Tests were successful. 

Currently the BCGNWS, Geomark, Open511 and BC Laws API specs have included the summary attribute.

Please proceed to add the summary attribute to the API specs of the geocoder, gated-geocoder, BCDC API and BC Route Planner.

**Comment by banders** [comment]
I added 'summary' to geocoder, gated-geocoder, BCDC and router.  Pull request is [here](https://github.com/bcgov/api-specs/pull/143).

**Comment by banders** [comment]
The above-noted pull request has been [merged](https://github.com/bcgov/api-specs/pull/143#event-953104003) into the api-specs master branch.  Let me know if any problems arise when the API specs are viewed in swagger-ui.
