### ISSUE TITLE
OpenAPI specs - Open links in new tab

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#32]
**Skills / SW**:
- OpenAPI spec (swagger 2.0)

**Description**:

- Fork OpenAPI specs located at the following repo.
   https://github.com/bcgov/api-specs
- Edit hyperlinks to open in a new tab. Currently the links below result in an error (scroll bar expands continuously) instead of opening the link in a new tab.

OpenAPI specs impacted: 

Geomark:
Links: see more at
          open gov license

BCGNWS:
Links: Crown copyright

BCLaws:
Links: Queens printer license

Geocoder:
Links: see more at
          open gov license

BCDC data api:
Links: hyperlinks in description section
          see more at
          open gov license

**Deliverables**:

- Pull request submitted for a new version of all OpenAPI specs

**Comment by BK01** [comment]
@ll911 @banders Browser used for OpenAPI console UAT - Chrome

**Comment by banders** [comment]
@BK01 I don't think this problem can be solved just by modifying the API spec files -- it requires a change to swagger-ui.

There is an existing [issue](https://github.com/swagger-api/swagger-ui/issues/1446) in the swagger-ui project, but it doesn't look like there's been any work on it yet.

**Comment by banders** [comment]
I have updated swagger-ui to use target=blank for all links displayed in the "Info" section (between the API title and the list of operations).  

I have made a custom build of swagger-ui which incorporates this change, and I have embedded the custom build into ckanext-openapiviewer.  The pull request is [here](https://github.com/bcgov/ckanext-openapiviewer/pulls).

**Comment by BK01** [comment]
Successful UAT complete using geocoder console in cad.data...

**Comment by BK01** [comment]
@BK01 to review this week

**Comment by BK01** [comment]
UAT complete in cat.data...
Ready for PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
