### ISSUE TITLE
Updated modal window for authorization

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#33]
**Skills / SW**:
- Swagger-ui

**Description**:

- Adjust the position of the swagger-ui modal window for authorization.
   (The modal window should appear closer to the top of the screen)

**Deliverables**:

- Updated swagger UI code

**Comment by banders** [comment]
I have created a patch to move the auth modal window nearer to the top of the page.  The patch is in [this branch](https://github.com/banders/swagger-ui/tree/auth_modal_position).  I have merged the branch into a custom build of swagger-ui for ckanext-openapiviewer.  My pull request for ckanext-openapiviewer is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/21).

**Comment by BK01** [comment]
@BK01 to test in CAD following merged pull request from @banders

**Comment by BK01** [comment]
@BK01 to review this week

**Comment by BK01** [comment]
UAT complete in cat.data...
Ready for PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
