### ISSUE TITLE
Contact the Developer

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#35]
**Skills / SW**:
- Swagger-ui

**Description**:

- Rename swagger-ui's "Contact the Developer" link
    This fix should be contributed back to the community 

**Deliverables**:
- Updated swagger UI code

**Comment by banders** [comment]
I fixed this issue in a new [branch ](https://github.com/banders/swagger-ui/tree/rename-contact-link) within my fork of swagger-ui.  As part of the fix, I improved the presentation of the entire "Info" section that is rendered between the API title and the list of operations.

I have not yet created a pull request to have the change merged back into core swagger-ui.  I will do that next week.

I have also created a new [branch](https://github.com/banders/swagger-ui/tree/for-ckanext-openapiviewer) which will combine all customizations of swagger-ui needed for the ckanext-openapiviewer project.  Currently the branch with ckanext-openapiviewer customizations incorporates the "Info" section changes described above, as well as the changes to support "HTML Markup" in response descriptions ([Issue 34](https://github.com/bcgov/DBC-APIM/issues/34)).

**Comment by BK01** [comment]
New contact information appears correct during UAT of cad.data...

Presented as (geocoder):

**Contact Information**
Contact Name: DataBC
Email: DataBCBA@gov.bc.ca
Website: https://forms.gov.bc.ca/databc-contact-us/

**Comment by banders** [comment]
Created a new [issue](https://github.com/swagger-api/swagger-ui/issues/2673) for this in the core swagger-ui repo.  The issue has a link the the pull request with my patch.

**Comment by BK01** [comment]
@BK01 to review this week

**Comment by BK01** [comment]
UAT complete in cat.data... 
Ready for PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
