### ISSUE TITLE
BCGNWS - 400 response

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#36]
**Skills / SW**:
- json, Swagger 2.0

**Description**:
- Update BCGNWS OpenAPI spec to include HTTP 400 response code.
- Links: [BCGNWS original OpenAPI spec issue](https://github.com/bcgov/DBC-APIM/issues/7)
             [BCGNWS OpenAPI spec](https://raw.githubusercontent.com/bcgov/api-specs/master/bcgnws/bcgnws.json)

Optional:
A. Examples section (see email) for each endpoint

**Deliverables**:
- Updated OpenAPI spec file for BCGNWS

**Comment by banders** [comment]
HTTP error code 400 and 404 responses have been added to the BCGNWS spec.  Merged pull request is [here](https://github.com/bcgov/api-specs/pull/139).
