### ISSUE TITLE
Swagger UI -API Keys

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#4]
**Skills / SW**:
- Swagger UI, OpenAPI spec (swagger 2.0)

**Description**:

Customize Swagger UI to add a textbox to allow the user to paste in their api key to reproduce behaviour shown in existing API Key console (examples below).

Route Planner
http://apps.gov.bc.ca/pub/api-explorer/?url=https://raw.githubusercontent.com/bcgov/api-specs/master/router/router.json

Gated Geocoder
http://apps.gov.bc.ca/pub/api-explorer/?url=https://raw.githubusercontent.com/bcgov/api-specs/master/geocoder/gated-geocoder.json

Also, add a new hyperlink to a fork of the following api spec that says "Click here for a developer API key". We don't have the developer API key request app built yet so for testing purposes please direct the link to the following URL "https://forms.gov.bc.ca/databc-contact-us/".

The objective here is to determine if it is possible to add a user friendly link or button to the API console. If not possible, we may alternatively add the hyperlink as plain text to the description section.

API spec (use a fork): 
https://github.com/bcgov/api-specs/blob/master/geocoder/gated-geocoder.json

**Sequencing**:
Given the existing timeline to migrate the OpenAPI CKAN extension to PROD BCDC we will use the following phased approach.

Phase 1:
Migrate new CKAN extension to PROD and use as the API console for public APIs such as BCGNWS, Geomark, Open511, BCLaws and the Geocoder. AT THE SAME TIME, API's that require API keys such as the gated geocoder and the bc route planner will continue to use their existing API consoles (added as a resource to the metadata record) as linked above in the description section.

Phase 2:
All APIs will use the new CKAN extension

**Future Plans - Context**:

When the Developer API key request tool is in PROD we can plan for a more automated approach (rather than copy & paste an API key into a text box). This will likely occur next fiscal unless otherwise stated. For the time being, the Swagger UI customisation to include a text box will meet business requirements.

**Deliverables**:

-  New customization for Swagger UI to add the api-key textbox into the embedded OpenAPI console found in BCDC.

- Sample OpenAPI spec (json) including the new additional link described above.
    -- Use an existing DataBC API swagger definition as the example (Gated Geocoder)

**Comment by BK01** [comment]
Interim strategy - public consoles use new OpenAPI console (CKAN), Keyed consoles use existing console.

**Comment by banders** [comment]
I just [committed](https://github.com/bcgov/ckanext-openapiviewer/commit/5ff4dba67466c221f280175d8ab9154156181360) a new version of ckanext-openapiviewer which upgrades to the latest version of swagger-ui (2.2.8) and adds the 'authorize' button to the OpenAPI Console resource view (visible for secure APIs only).  The 'authorize' button provides a means to specify an API key that will be sent along with any requests tested through the OpenAPI Console.

@ll911 mentioned that 2.2.8 is slower to load in some cases.  Let me know if there is any unacceptable slowness visible with our deployment of ckanext-openapiviewer in CKAN.

Note that swagger-ui requires a few different CORS response headers (such as Access-Control-Allow-Methods and Access-Control-Allow-Headers) in the openapi-json spec files in order for authorizations (e.g. API keys) to work.  Those headers aren't returned by Github.  That presents a problem for openapi-json spec files describing secure APIs which are stored in Github.  One solution is to instead store secure spec files on the same server (same origin) as that which is running CKAN and the ckanext-openapiviewer extension.

**Comment by banders** [comment]
I have created a [branch](https://github.com/banders/swagger-ui/tree/request-api-key-link) in my fork of swagger-ui which adds a new button "Request Key".  Currently the button just links to a DataBC Contact Us page, but in the future it can be tied to the API key service.

I have merged the new branch into a custom build of swagger-ui for ckanext-openapiviewer.  The Pull request for ckanext-openapiviewer is [here](https://github.com/bcgov/ckanext-openapiviewer/pull/21).

**Comment by BK01** [comment]
@BK01 to test in CAD following merged pull request from @banders

**Comment by BK01** [comment]
@BK01 to review this week

**Comment by BK01** [comment]
UAT complete in cat.data...
Ready for PROD.

**Comment by BK01** [comment]
Ready to migrate to PROD.
