### ISSUE TITLE
Heartbeat - Chart Sorting

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#40]
**Skills / SW**:
- JavaScript, HTML

**Background**:
https://github.com/bcgov/dbcrss/blob/master/heartbeat/README.md

**Description**:
> Update the JavaScript to show the chart order as most recent days first.
> Fork and adjust as necessary. This repo uses both master and gh-pages branch.

- Current JavaScript files for reference:
https://github.com/bcgov/dbcrss/tree/master/heartbeat/src/d3

- Same JavaScript files, but used with heartbeat pages
https://github.com/bcgov/dbcrss/tree/gh-pages/heartbeat

**Potential references**:
https://github.com/d3/d3/wiki/Time-Scales 
https://www.dashingd3js.com/d3js-scales

**Comment by banders** [comment]
I forked this repo and [committed ](https://github.com/banders/dbcrss/commit/35fa1e8f4cd718e3d7f03f7ee1a24fa2b4401f67)a patch to change the chart order (newest to oldest).  Pull request is [here](https://github.com/bcgov/dbcrss/pull/2).

**Comment by banders** [comment]
Revised pull request [here](https://github.com/bcgov/dbcrss/pull/3) has been merged.  Chart sorting is complete and ready for review.
