### ISSUE TITLE
Heartbeat - Python parameters

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#44]
**Skills / SW**:
- Python

**Background**:
https://github.com/bcgov/dbcrss/blob/master/heartbeat/README.md

**Description**:
> Investigate and implement a new approach to passing in the request URLs to the python script. Currently the URLs are hardcoded and API key passed in as an argument. Is it possible to update the python script to be more generic and therefore universal to be used for other API request URLs?
> Fork and adjust as necessary. This repo uses both master and gh-pages branch.

- Current JavaScript files for reference:
https://github.com/bcgov/dbcrss/tree/master/heartbeat/src/d3

- Same JavaScript files, but used with heartbeat pages
https://github.com/bcgov/dbcrss/tree/gh-pages/heartbeat

**Potential references**:
https://github.com/d3/d3/wiki/Time-Scales 
https://www.dashingd3js.com/d3js-scales

**Comment by BK01** [comment]
DataBC to provide demo key.

**Comment by banders** [comment]
I have modified the python script to accept two parameters:

-url <URL TO TEST>
-o <OUTPUT FILENAME>

The script can now be used to test the heartbeat of arbitrary URLs.  Pull request is [here](https://github.com/bcgov/dbcrss/pull/5).

Note: the Jenkins job that calls Heartbeat.py must be modified to call the script one time for each API being tested.  Each call must be made with appropriate parameters.  Example calls are given in the comments at the top of the .py file.
