### ISSUE TITLE
Heartbeat - Status check

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#47]
Enable python script to check if web services are online that don't necessarily have the execution time listed in response.

Perform this for Geomark and BCGNWS.

Output: textfile as well as JS, HTML visual chart. 

This issue covers issues #24 and issue #6

**Comment by banders** [comment]
I have modified the Heartbeat.py script to support APIs that:

- don't return execution time
- don't return JSON
- don't return kong latency headers

Also improved error handling.

Pull request is [here](https://github.com/bcgov/dbcrss/pull/6).

**Comment by banders** [comment]
I have also modified the 'gh-pages' branch to include heartbeat graphs for BCGNWS and Geomark. 

Pull request is [here](https://github.com/bcgov/dbcrss/pull/8).
