### ISSUE TITLE
OpenAPI spec - model

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#50]
See bottom of console

http://petstore.swagger.io/

**Comment by BK01** [comment]
To be completed after existing OpenAPI specs are upgraded, along with swagger-ui.

**Comment by BK01** [comment]
To add to BCGNWS spec for review in cad.data. Following UAT, other specs may also be updated as listed.

**Comment by banders** [comment]
@BK01 I recall a previous conversation in which we discussed that the output of web services tends to change more often than the interfaces.  If we add the output "models" to the OAS specs we'll be obliged to keep them up-to-date which could become a headache.  In my opinion a more practical record of the output "model" is an example of the output itself, which users can already generate via "Try it out".  Thoughts?

**Comment by BK01** [comment]
Fair point, let's place this item on hold
