### ISSUE TITLE
CKAN extension - Galileo Agent (python)

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#54]
Estimate: CKAN extension to use python Galileo agent. 

Send call to Galileo, list of apps, select an app, display reports.

DataBC create Galileo endpoint, token stored as config item in extension. Extension feeds BCDC logs into Galileo.

No visual component in extension, as it relies on Galileo. Could serve as a google analytics replacement if needed in future.

Docs:
Galileo Agent Spec: https://github.com/Mashape/galileo-agent-spec
Galileo API: see version 1.1.1 of specs in above link

Next steps:
> DataBC description
> Brock - Research and provide estimate.

**Comment by BK01** [comment]
To provide estimate.
Future: analytics to BCDC team

**Comment by banders** [comment]
@BK01 I estimate this task will take about three days effort.

**Comment by banders** [comment]
@BK01 @ll911 is there a github repository for this new extension yet?  If not, perhaps you can create an empty repo as a starting point for this work...

**Comment by ll911** [comment]
@banders https://github.com/bcgov/ckanext-galileo

**Comment by ll911** [comment]
need to create access token for this

**Comment by banders** [comment]
@ll911 Can you send me the galileo service token when you have a chance?  Thanks!

**Comment by BK01** [comment]
To confirm endpoint being used and version dependency (virt env?). @ll911 to provide details.

**Comment by banders** [comment]
the mashape-analytics python agent shares some dependencies with CKAN, but requires slightly different versions.  This causes dependency conflicts when running CKAN.  I suspect mashape-analytics doesn't need to be so strict with the dependency versions it requires, and I have requested they specify minimum versions in their setup.py file instead of exact versions:

https://github.com/Mashape/analytics-agent-python/issues/8

**Comment by banders** [comment]
@ll911 @BK01 I have committed the initial version of the ckanext-galileo plugin:

https://github.com/bcgov/ckanext-galileo

Can you try installing this in the delivery environment?  The readme has install instructions.

**Comment by BK01** [comment]
DataBC to deploy. Mashape analytics python library dependencies are in conflict. @ll911 investigating resolution.

**Comment by BK01** [comment]
DataBC to look into options including embedding MA within the plugin, or running the plugin within a container (virtual environment) to avoid dependency conflicts.

**Comment by BK01** [comment]
DataBC to try following CKAN 2.7 update

**Comment by BK01** [comment]
On hold until Galileo license is confirmed
