### ISSUE TITLE
OpenAPI spec - Gated Geocoder

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#56]
Update the gated Geocoder spec to match the public geocoder spec at the following location.

https://github.com/bcgov/api-specs/tree/master/geocoder/

Exceptions include the api key (not used in public) as well as the host. Otherwise, parameters, resources and examples should be the same.

**Comment by BK01** [comment]
Test: Compare 2x existing geocoder OpenAPI specs. Merge OpenAPI specs for pub and gated geocoder into a single OpenAPI 3 spec. Add instructions to tell user to avoid key if using pub.

Consider using 'server' option.

**Comment by banders** [comment]
@BK01 @ll911 I updated the gated geocoder spec to pull in Michael's recent changes to the public spec.  The file is still in openapi 2 format.  Pull request is [here](https://github.com/bcgov/api-specs/pull/249).

I transformed the public and gated geocoder specs to openapi3.  Those files are available in [this branch](https://github.com/banders/api-specs/tree/upgrade-to-openapi3/geocoder) of my repo.

I also created a new geocoder spec file which combines the public and gated specs.  The [combined spec file](https://github.com/banders/api-specs/blob/upgrade-to-openapi3/geocoder/geocoder-combined.json) is written in openapi 3 format.

**Comment by BK01** [comment]
To review release notes for enhancements / bug fixes. @banders to test new release in delivery.

**Comment by BK01** [comment]
DataBC to begin UAT in cad.data

**Comment by BK01** [comment]
UAT complete. Redundant issue. Covered by #49
