### ISSUE TITLE
OpenAPI spec - Geomark

### ISSUE THREAD

**Issue by BK01** [bcgov/DBC-APIM#64]
Add the missing 'allowOverlap' parameter to the Geomark OpenAPI spec.

Add to the following areas:
> /geomarks/new
> /geomarks/copy

Default: Not selected, optional to include in POST request.
Selected: allowOverlap = true

Description text:
"For Geometry Count=Many select this option to allow overlapping geometries"

Current version:
https://raw.githubusercontent.com/bcgov/api-specs/master/geomark/geomark.json

Example UI with allow overlap:
http://apps.gov.bc.ca/pub/geomark/geomarks#file

Documentation:
http://apps.gov.bc.ca/pub/geomark/docs/rest-api/

**Comment by BK01** [comment]
Update OpenAPI spec (current PROD version) in api-specs repo
Also create a new OpenAPI 3 spec in your repo

**Comment by banders** [comment]
@BK01 I see that the rest api documentation page listed above doesn't specify the available parameters for the "[new](http://apps.gov.bc.ca/pub/geomark/docs/rest-api/#ca_bc_gov_geomark_web_rest_Geomark_createGeomark)" and "copy" resources.  

I hoped to refer to the docs to confirm that "allowOverlap" is the correct parameter name (and not just a human-readable label) and that it is indeed also available in the "copy" resource. Our current API spec doesn't have a parameter for Geometry Count=many on the "copy" resource, so I thought that perhaps "allowOverlap" doesn't apply either.  

Is there any other place I can find an authoritative list of parameters for the geomark api?

**Comment by BK01** [comment]
Other than the link below, we have mainly used fiddler to examine the POST request. We can connect with the Geomark vendor to verify the parameters beyond the link below.

http://apps.gov.bc.ca/pub/geomark/docs/

**Comment by BK01** [comment]
Verified.

/geomarks/new
 
To allow overlaps:
            allowOverlap=true
            multiple=true
 
/geomarks/copy
 
To allow overlaps:
             allowOverlap=true

Sample UI with all allowed parameters:

http://apps.gov.bc.ca/pub/geomark/geomarks#file
http://apps.gov.bc.ca/pub/geomark/geomarks#geomarks

**Comment by banders** [comment]
Thanks @BK01.  I added the 'allowOverlap' param to the 'new' and 'copy' resources of the OAS 2 spec file.  PR is [here](https://github.com/bcgov/api-specs/pull/252).

**Comment by banders** [comment]
And I also added the 'allowOverlap' param to the OAS 3 spec file, which currently resides in my repo [here](https://github.com/banders/api-specs/blob/upgrade-to-openapi3/geomark/geomark.json).

**Comment by BK01** [comment]
Merge of OAS 2 spec file complete.

**Comment by BK01** [comment]
UAT complete
