### ISSUE TITLE
API specs for WFS, WMS etc

### ISSUE THREAD

**Issue by ll911** [bcgov/DBC-APIM#92]
from @webgismd,
need sth like https://www.npmjs.com/package/wfs2swagger to produce Open API specs for our current WFS/WMS,etc
maybe align with incoming WFS3 ?
https://github.com/opengeospatial/WFS_FES 
https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html

**Comment by BK01** [comment]
Issue text merged with #93
